### ISSUE TITLE
How to unmount only one volume

### ISSUE THREAD

**Issue by xastherion** [henri/ejector#1]
Hi Henry,
Thank you for your Script. Work like a charm!

For my nedeed, i want only one volume that not mount, but users should use USB-sticks or anothers disks. That is because i have dual boot there and macOS mounted allways the old partition and somethings like Spotlight find the old software by typing, to make many problems by p.e. Adobe Applications.

I realise this with ejector and put in eject.sh the path of the whole volume i dont want to automount, so:
"... | grep /Volumes/oldvolume | ..."

and run beatiful like i need. Maybe you can put this as functionality someware for another guys or easy in the #documentation am script. Is a Idee.

Best Regards!

**Comment by henri** [comment]
Glad you have something working. If you just want to prevent a particular partition from mounting you may want to take a look at the following : http://www.lbackup.org/developer/mounting_attached_backup_devices

The link which will be of particular interest will be towards the top of the page and which will take you to information (now on the internet archive) about the fstab.
